/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hu.gdf;

import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Erős Ákos <wlxgpb@neptun.gdf.hu>
 */
public class GameWindow extends javax.swing.JFrame {

    private GameDemo game;
    
    /**
     * Creates new form GameFrame
     */
    public GameWindow(GameDemo game) {
        this.game = game;
        initComponents();
        updateActorList();
    }
    
    public void updateActorList() {
        List<Actor> actors = game.getActors();
        DefaultListModel<Actor> model = new DefaultListModel<>();
        model.addAll(actors);
        actorList.setModel(model);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FramePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        actorList = new javax.swing.JList<>();
        nameButton = new javax.swing.JButton();
        levelButton = new javax.swing.JButton();
        fightButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        actorList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        actorList.setModel(new DefaultListModel<>());
        jScrollPane1.setViewportView(actorList);

        nameButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameButton.setText("List by name");

        levelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        levelButton.setText("List by level");

        fightButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fightButton.setText("Fight");

        infoArea.setColumns(20);
        infoArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        infoArea.setRows(5);
        jScrollPane2.setViewportView(infoArea);

        javax.swing.GroupLayout FramePanelLayout = new javax.swing.GroupLayout(FramePanel);
        FramePanel.setLayout(FramePanelLayout);
        FramePanelLayout.setHorizontalGroup(
            FramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FramePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(FramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(FramePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                        .addGroup(FramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(levelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );
        FramePanelLayout.setVerticalGroup(
            FramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FramePanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(FramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(FramePanelLayout.createSequentialGroup()
                        .addComponent(nameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(levelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(fightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FramePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FramePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FramePanel;
    private javax.swing.JList<Actor> actorList;
    private javax.swing.JButton fightButton;
    private javax.swing.JTextArea infoArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton levelButton;
    private javax.swing.JButton nameButton;
    // End of variables declaration//GEN-END:variables
}
