/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hu.gdf;

import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Erős Ákos <wlxgpb@neptun.gdf.hu>
 */
public class GameWindow extends javax.swing.JFrame {

    private GameDemo game;
    
    /**
     * Creates new form GameFrame
     */
    public GameWindow(GameDemo game) {
        this.game = game;
        initComponents();
        updateActorList(true);
    }
    
    public void updateActorList(boolean listByName) {
        List<Actor> actors = game.getActors();
        DefaultListModel<Actor> model = new DefaultListModel<>();
        if (listByName) {
            Collections.sort(actors);
        } else {
            Comparator<Actor> levelComparator = (a1, a2) -> Integer.valueOf(a2.getLevel()).compareTo(a1.getLevel());
            actors.sort(levelComparator);
        }
        model.addAll(actors);
        actorList.setModel(model);
        
    }
    
    public void displayOnWindow(StringBuilder text) {
        infoArea.setText(infoArea.getText()
                .concat(text.toString())
                .concat("\n"));
        infoArea.setCaretPosition(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FramePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        actorList = new javax.swing.JList<>();
        nameButton = new javax.swing.JButton();
        levelButton = new javax.swing.JButton();
        fightButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        actorList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        actorList.setModel(new DefaultListModel<>());
        jScrollPane1.setViewportView(actorList);

        nameButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameButton.setText("List by name");
        nameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameButtonActionPerformed(evt);
            }
        });

        levelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        levelButton.setText("List by level");
        levelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelButtonActionPerformed(evt);
            }
        });

        fightButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fightButton.setText("Fight");
        fightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fightButtonActionPerformed(evt);
            }
        });

        infoArea.setColumns(20);
        infoArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        infoArea.setRows(5);
        jScrollPane2.setViewportView(infoArea);

        javax.swing.GroupLayout FramePanelLayout = new javax.swing.GroupLayout(FramePanel);
        FramePanel.setLayout(FramePanelLayout);
        FramePanelLayout.setHorizontalGroup(
            FramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FramePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FramePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(FramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(levelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fightButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE))
                .addContainerGap())
        );
        FramePanelLayout.setVerticalGroup(
            FramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FramePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FramePanelLayout.createSequentialGroup()
                        .addComponent(nameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(levelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(fightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FramePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FramePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameButtonActionPerformed
        updateActorList(true);
    }//GEN-LAST:event_nameButtonActionPerformed

    private void levelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelButtonActionPerformed
        updateActorList(false);
    }//GEN-LAST:event_levelButtonActionPerformed

    private void fightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fightButtonActionPerformed
        game.simulateFight();
    }//GEN-LAST:event_fightButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FramePanel;
    private javax.swing.JList<Actor> actorList;
    private javax.swing.JButton fightButton;
    private javax.swing.JTextArea infoArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton levelButton;
    private javax.swing.JButton nameButton;
    // End of variables declaration//GEN-END:variables
}
